Default: &defaults
  host: "localhost"
  port: 3000
  copyright: Except where otherwise noted, content on this site is licensed under a Creative Commons BY-NC-SA 3.0 License.
  #analytics: UA-YOURCODE
  verification: fHM_yAw2cluSQ1j0USmMnj3SwZXeKCQrYzkCC71Zado
  jquery: https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.shergill.su"
  port: 53000
  <<: *defaults
