language: haskell
sudo: false

addons:
  apt:
    packages:
      - ruby
      - rubygems

before_install:
  - cd blog
  - make build-ci

install:
  - cd blog
  - make travis v=0
  - hsenv && . .hsenv/bin/activate
  - make setup v=0

script:
  - make build

notifications:
  irc: "irc.freenode.org#shergill"
  use_notice: true
  # email:
  #   - suhailshergill@gmail.com
  # on_success: change
  # on_failure: always

